Repository tea-kkeul/Tea-KKeul-iOS, pull requests merged in 2022-01, with the labels that each got.

#12 Feat/#8 magazine proto
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS/Global/Struct/Identifiers.swift
  Tea-KKeul-iOS/Screen/Magazine/Cell/CVC/MagazineCVC.swift
  Tea-KKeul-iOS/Screen/Magazine/Controller/MagazineVC.swift
  Tea-KKeul-iOS/Screen/Magazine/Storyboard/Magazine.storyboard
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine1.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine1.imageset/magazine1.png
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine2.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine2.imageset/magazine2.png
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine3.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine3.imageset/magazine3.png
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine4.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine4.imageset/magazine4.png
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine5.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine5.imageset/magazine5.png
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine6.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/magazine6.imageset/magazine6.png
Labels: enhancement, View, 윤경, 매거진뷰

#14 Add/#13 tabBar and extension
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS/Global/Extension/Notification+Name.swift
  Tea-KKeul-iOS/Global/Extension/UIButton+.swift
  Tea-KKeul-iOS/Global/Extension/UIColor+.swift
  Tea-KKeul-iOS/Global/Extension/UIFont+.swift
  Tea-KKeul-iOS/Global/Extension/UILabel+.swift
  Tea-KKeul-iOS/Global/Extension/UITextField+.swift
  Tea-KKeul-iOS/Screen/Magazine/Cell/CVC/MagazineCVC.swift
  Tea-KKeul-iOS/Screen/Magazine/Controller/MagazineVC.swift
  Tea-KKeul-iOS/Screen/Magazine/Storyboard/Magazine.storyboard
  Tea-KKeul-iOS/Screen/TabBar/Controller/TeaKKeulTBC.swift
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Calendar.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Calendar.imageset/Tab_Calendar.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Calendar_Selected.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Calendar_Selected.imageset/Tab_Calendar_Selected.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Home.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Home.imageset/Tab_Home.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Home_Selected.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Home_Selected.imageset/Tab_Home_Selected.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Magazine.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Magazine.imageset/Tab_Magazine.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Magazine_Selected.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Magazine_Selected.imageset/Tab_Magazine_Selected.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Mypage.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Mypage.imageset/Tab_Mypage.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Mypage_Selected.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Tab_Mypage_Selected.imageset/Tab_Mypage_Selected.png
Labels: enhancement, 윤경

#17 [FEAT]: MagazineWebView-open as Safari in app
  Tea-KKeul-iOS/Screen/Magazine/Controller/MagazineVC.swift
Labels: enhancement, View, 윤경, 매거진뷰

#18 [Feat] google login
  Podfile
  Podfile.lock
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS/Screen/Login/Controller/LoginVC.swift
  Tea-KKeul-iOS/Screen/Login/Storyboard/Login.storyboard
  Tea-KKeul-iOS/Support/AppDelegate.swift
  Tea-KKeul-iOS/Support/Info.plist
Labels: 내림, 로그인뷰

#19 [FEAT] 홈 화면 구성하기
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS/Global/Struct/Identifiers.swift
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/ConditionCheckTVC.swift
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/ConditionCheckTVC.xib
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/HomeTitleHeaderView.swift
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/HomeTitleHeaderView.xib
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/MyStateTVC.swift
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/MyStateTVC.xib
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/SubscribeTVC.swift
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/SubscribeTVC.xib
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/TeaListTVC.swift
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/TeaListTVC.xib
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/b.swift
  Tea-KKeul-iOS/Screen/Home/Controller/HomeVC.swift
  Tea-KKeul-iOS/Screen/Home/Storyboard/Home.storyboard
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 454.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 454.imageset/Group 454.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 454.imageset/Group 454@2x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 454.imageset/Group 454@3x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 466.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 466.imageset/Group 466.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 466.imageset/Group 466@2x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 466.imageset/Group 466@3x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 467.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 467.imageset/Group 467.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 467.imageset/Group 467@2x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 467.imageset/Group 467@3x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 470.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 470.imageset/Group 470.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 470.imageset/Group 470@2x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 470.imageset/Group 470@3x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 471.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 471.imageset/Group 471.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 471.imageset/Group 471@2x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 471.imageset/Group 471@3x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 484.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 484.imageset/Group 484.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 484.imageset/Group 484@2x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 484.imageset/Group 484@3x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 485.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 485.imageset/Group 485.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 485.imageset/Group 485@2x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Group 485.imageset/Group 485@3x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Vector 6.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Vector 6.imageset/Vector 6.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Vector 6.imageset/Vector 6@2x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Vector 6.imageset/Vector 6@3x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/button_empty-1.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/button_empty-1.imageset/button_empty.png
  Tea-KKeul-iOS/Support/Assets.xcassets/button_empty-1.imageset/button_empty@2x.png
  Tea-KKeul-iOS/Support/Assets.xcassets/button_empty-1.imageset/button_empty@3x.png
Labels: 윤진, 홈뷰

#23 Feat/#21 mypage view
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS/Global/Struct/Identifiers.swift
  Tea-KKeul-iOS/Screen/Mypage/Cell/TVC/SettingTVC.swift
  Tea-KKeul-iOS/Screen/Mypage/Controller/MypageVC.swift
  Tea-KKeul-iOS/Screen/Mypage/Storyboard/Mypage.storyboard
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList.imageset/LikeList.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV1.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV1.imageset/Mypage_TV1.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV2.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV2.imageset/Mypage_TV2.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV3.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV3.imageset/Mypage_TV3.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV4.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV4.imageset/Mypage_TV4.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV5.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV5.imageset/Mypage_TV5.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV6.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV6.imageset/Mypage_TV6.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV7.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Mypage_TV7.imageset/Mypage_TV7.png
  Tea-KKeul-iOS/Support/Assets.xcassets/ProfileImg.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/ProfileImg.imageset/ProfileImg.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Setting.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Setting.imageset/Setting.png
  Tea-KKeul-iOS/Support/Assets.xcassets/SubscribeList.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/SubscribeList.imageset/SubscribeList.png
Labels: enhancement, View, 윤경, 마이페이지뷰

#25 [Feat] apple login -ing
  Podfile
  Podfile.lock
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS.xcodeproj/xcshareddata/xcschemes/Tea-KKeul-iOS.xcscheme
  Tea-KKeul-iOS/Screen/Login/Controller/LoginVC.swift
  Tea-KKeul-iOS/Support/AppDelegate.swift
  Tea-KKeul-iOS/Tea-KKeul-iOS.entitlements
Labels: enhancement, 내림, 로그인뷰

#27 Feat/#24 mypage delivery view
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS/Global/Factory/TypeOfViewController.swift
  Tea-KKeul-iOS/Global/Struct/Identifiers.swift
  Tea-KKeul-iOS/Screen/Mypage/Cell/CVC/AddressCVC.swift
  Tea-KKeul-iOS/Screen/Mypage/Cell/CVC/AddressEnrollCVC.swift
  Tea-KKeul-iOS/Screen/Mypage/Controller/DeliveryListVC.swift
  Tea-KKeul-iOS/Screen/Mypage/Controller/MypageNC.swift
  Tea-KKeul-iOS/Screen/Mypage/Controller/MypageVC.swift
  Tea-KKeul-iOS/Screen/Mypage/Storyboard/DeliveryList.storyboard
  Tea-KKeul-iOS/Screen/Mypage/Storyboard/Mypage.storyboard
Labels: enhancement, View, 윤경, 마이페이지뷰

#29 Feat/#28 like list view proto
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS/Global/Struct/Identifiers.swift
  Tea-KKeul-iOS/Screen/Mypage/Cell/CVC/LikeListCVC.swift
  Tea-KKeul-iOS/Screen/Mypage/Controller/LikeListVC.swift
  Tea-KKeul-iOS/Screen/Mypage/Controller/MypageVC.swift
  Tea-KKeul-iOS/Screen/Mypage/Storyboard/LikeList.storyboard
  Tea-KKeul-iOS/Screen/Mypage/Storyboard/Mypage.storyboard
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeBtn.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeBtn.imageset/LikeBtn.png
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeBtn_UnSelected.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeBtn_UnSelected.imageset/LikeBtn_UnSelected.png
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList_CV1.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList_CV1.imageset/LikeList_CV1.png
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList_CV2.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList_CV2.imageset/LikeList_CV2.png
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList_CV3.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList_CV3.imageset/LikeList_CV3.png
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList_CV4.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/LikeList_CV4.imageset/LikeList_CV4.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Star.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Star.imageset/Star.png
Labels: enhancement, View, 윤경, 마이페이지뷰

#30 Feature/#9-CalendarView Proto구현
  Tea-KKeul-iOS/Screen/Calendar/Controller/CalendarVC.swift
  Tea-KKeul-iOS/Screen/Calendar/Storyboard/Calendar.storyboard
  Tea-KKeul-iOS/Support/Assets.xcassets/NextBtn.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/NextBtn.imageset/NextBtn.png
  Tea-KKeul-iOS/Support/Assets.xcassets/PrevBtn.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/PrevBtn.imageset/PrevBtn.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_1.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_1.imageset/Status_1.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_2.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_2.imageset/Status_2.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_3.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_3.imageset/Status_3.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_4.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_4.imageset/Status_4.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_5.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Status_5.imageset/Status_5.png
Labels: enhancement, View, 은비, 캘린더뷰

#35 Feat/#31 calendar view design
  Tea-KKeul-iOS/Screen/Calendar/Controller/CalendarVC.swift
  Tea-KKeul-iOS/Screen/Calendar/Storyboard/Calendar.storyboard
  Tea-KKeul-iOS/Support/Assets.xcassets/NextBtn.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/PrevBtn.imageset/Contents.json
Labels: enhancement, View, 은비, 캘린더뷰

#36 Feat/#32 onboarding view
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS/Global/Struct/Identifiers.swift
  Tea-KKeul-iOS/Screen/Onboarding/Controller/OnboardingBaseVC.swift
  Tea-KKeul-iOS/Screen/Onboarding/Controller/OnboardingVC.swift
  Tea-KKeul-iOS/Screen/Onboarding/Storyboard/Onboarding.storyboard
  Tea-KKeul-iOS/Screen/Onboarding/Storyboard/OnboardingBase.storyboard
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_1.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_1.imageset/Onboarding_1.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_2.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_2.imageset/Onboarding_2.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_3.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_3.imageset/Onboarding_3.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_4.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_4.imageset/Onboarding_4.png
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_5.imageset/Contents.json
  Tea-KKeul-iOS/Support/Assets.xcassets/Onboarding_5.imageset/Onboarding_5.png
  Tea-KKeul-iOS/Support/Info.plist
Labels: enhancement, View, 윤경, 온보딩뷰

#40 [FEAT]: PurchaseCompleteView
  Tea-KKeul-iOS.xcodeproj/project.pbxproj
  Tea-KKeul-iOS/Global/Struct/Identifiers.swift
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/SubscribeTVC/PaymentSelectionTVC.swift
  Tea-KKeul-iOS/Screen/Home/Cell/TVC/SubscribeTVC/PaymentSelectionTVC.xib
  Tea-KKeul-iOS/Screen/Home/Controller/SubscribeVC.swift
  Tea-KKeul-iOS/Screen/Home/Storyboard/Subscribe.storyboard
  Tea-KKeul-iOS/Screen/Purchase/Controller/PurchaseCompleteVC.swift
  Tea-KKeul-iOS/Screen/Purchase/Storyboard/PurchaseComplete.storyboard
  Tea-KKeul-iOS/Support/Info.plist
Labels: enhancement, View, 윤경
